name: autotest

on: [push, pull_request]

jobs:
  test: 
    runs-on: ubuntu-latest

    steps: 
      - name: checkout
        uses: actions/checkout@v4

      - name: installing Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.11'

      - name: installing libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: running test
        run: python -m unittest discover
        
